<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_true_nawatable-row2-delete</name>
   <tag></tag>
   <elementGuidId>43a2bae3-494a-40ee-8eeb-97364bd7e575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nawatable-row2-delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nawatable-row2-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1c6d7d5-c075-47d3-b463-d7bdd6a39a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root</value>
      <webElementGuid>ec230a39-aee2-46f7-abae-ec15cf2963b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>09792707-4c69-4e3a-8a8f-d2e70423a629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b5a75ae-8746-462c-ae1f-3ebc941e7660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>c0c9b852-246d-4443-98fb-fe53e3e63602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>e203b32d-e780-405f-941d-27f6ffd6a1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nawatable-row2-delete</value>
      <webElementGuid>28dba409-0435-451c-a6d2-cbaf5e41314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-65777</value>
      <webElementGuid>a17b8a14-9028-4c8e-b6af-e54bdc658253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nawatable-row2-delete&quot;)</value>
      <webElementGuid>1e7eecd8-0ae1-49b7-8669-e2fa08d50270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nawatable-row2-delete']</value>
      <webElementGuid>5bedfd1f-7e16-4591-a311-b00c1ea418ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nawatable-container-Group Menu']/div[4]/div/table/tbody/tr[2]/td[9]/button[2]</value>
      <webElementGuid>246f73d5-c5d2-4267-9298-e54ce3ac1c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[2]/following::button[2]</value>
      <webElementGuid>5e4f60e7-9a12-4b0b-b299-fa88dec720d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Checker'])[1]/following::button[2]</value>
      <webElementGuid>d6a15736-d6c9-4a9b-b73d-e42f1acd515f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ops Team Maker'])[1]/preceding::button[3]</value>
      <webElementGuid>6fcc7750-496c-4427-84c5-194e6ef906c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[3]/preceding::button[3]</value>
      <webElementGuid>27112542-1fca-43e1-b5d9-f348c0d32980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[9]/button[2]</value>
      <webElementGuid>bcfe9405-bf44-4ed3-a8ef-88de5cb1d74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'nawatable-row2-delete']</value>
      <webElementGuid>f9d93aea-a466-4127-a628-7371520967f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
