<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_true_nawatable-row2-activation</name>
   <tag></tag>
   <elementGuidId>4e439021-3ea7-4433-a6c4-d16cb11bb1fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nawatable-row2-activation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nawatable-row2-activation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1e95f81-99ce-494a-8ba1-ab1b206e819a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root</value>
      <webElementGuid>5310e25b-c779-4a20-8ecf-c7521cf0c0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24ea68a6-8660-457f-8098-493d8ed92638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51903c53-dbd3-4d5d-a13e-f0e05e159efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>d505c7ac-73e0-457e-ab7f-0efbcb81eb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Activation</value>
      <webElementGuid>7c1dec39-ec50-403f-8990-5f90ad18b3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nawatable-row2-activation</value>
      <webElementGuid>b8a56f63-a44e-4946-9ff3-18512b0785b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-66480</value>
      <webElementGuid>a2f83c79-cffd-4f00-94ea-dc6e9906505b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nawatable-row2-activation&quot;)</value>
      <webElementGuid>7af2610f-c79e-4b97-892b-6687df9a7d01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nawatable-row2-activation']</value>
      <webElementGuid>793e80c8-721f-49c5-b4e8-c06de97baa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nawatable-container-Group Menu']/div[4]/div/table/tbody/tr[2]/td[9]/button[4]</value>
      <webElementGuid>7c507533-e7e2-4c96-a1ae-3ccad502ef80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[2]/following::button[4]</value>
      <webElementGuid>f1a51905-a7a6-47dc-93b9-a4f2db809fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Checker'])[1]/following::button[4]</value>
      <webElementGuid>5fdecdb2-624a-4357-ad0c-295638a60a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ops Team Maker'])[1]/preceding::button[1]</value>
      <webElementGuid>7e75703b-4146-47eb-833d-0590f42dbdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[3]/preceding::button[1]</value>
      <webElementGuid>28fb359d-0dde-4f35-82b2-3ae49e2ea565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[9]/button[4]</value>
      <webElementGuid>9bbb7238-ec4e-4ffe-820e-50d9553c1144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'nawatable-row2-activation']</value>
      <webElementGuid>37b21c93-976c-423a-a47d-5b8d73b9d88e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
