<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_true_nawatable-row3-details</name>
   <tag></tag>
   <elementGuidId>6e5e6daf-f2ef-4dd0-a7a3-86b08101e1ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nawatable-row3-details']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nawatable-row3-details</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85d6458a-5640-499f-ae51-6c7944b8d651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root</value>
      <webElementGuid>7fc6636e-5799-4a2a-a784-28359af2dd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>71d8ce53-49f2-4e41-a52a-5ce21450a57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bad790ec-2c48-4a42-b857-f69ce385067a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>6b64fb8c-99c0-4ade-a289-8a4f86626eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Details</value>
      <webElementGuid>8f5050c2-59c9-444e-a5e0-f0f850306478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nawatable-row3-details</value>
      <webElementGuid>11506082-366b-4547-b84b-023eba9d9c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-3212</value>
      <webElementGuid>37b6b0ac-0a6f-4eda-8fed-8f20ad44f71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nawatable-row3-details&quot;)</value>
      <webElementGuid>4e09e2b9-6f2c-428a-9384-9639163988ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nawatable-row3-details']</value>
      <webElementGuid>df1c90b5-49a3-4a8e-9fab-1670af07619a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nawatable-container-Group Menu']/div[4]/div/table/tbody/tr[3]/td[9]/button[3]</value>
      <webElementGuid>9d4586fd-c88e-4afa-82b5-8abf6c084854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[3]/following::button[3]</value>
      <webElementGuid>451b01f6-578a-435b-9b98-fe7aeccee639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ops Team Maker'])[1]/following::button[3]</value>
      <webElementGuid>2187ec0d-09d6-4c02-a465-95d957ff7496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ops Team Checker'])[1]/preceding::button[2]</value>
      <webElementGuid>66600deb-a411-414e-b2a9-43c9cf4a52f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[4]/preceding::button[2]</value>
      <webElementGuid>3d3c95e1-7c82-41f2-a106-83fbff492782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[9]/button[3]</value>
      <webElementGuid>3c50d850-9fcf-4fe0-925d-3d919722d83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'nawatable-row3-details']</value>
      <webElementGuid>3777433d-9223-4905-bfc1-66919c8fac91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
