<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_true_nawatable-row3-activation</name>
   <tag></tag>
   <elementGuidId>1899b477-80a2-4c64-b934-c6370caa1e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nawatable-row3-activation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nawatable-row3-activation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12105c40-c64d-42cf-ba65-82ad461a40a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root</value>
      <webElementGuid>06b2f48a-818f-439d-bdc4-7a41fdc67143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1419d03b-1166-4998-a54e-0dee52de3c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dec90548-fb89-4538-afd4-586b135d3857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>4530add7-cbe2-4de3-ab6a-3bb139b135c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Activation</value>
      <webElementGuid>0bdcbf0c-4a77-4eb0-84ad-a06f99338d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nawatable-row3-activation</value>
      <webElementGuid>2cdebbb9-fa5c-433c-abb6-1bb079190e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-79673</value>
      <webElementGuid>0186fed0-e838-4806-ab55-f59134551d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nawatable-row3-activation&quot;)</value>
      <webElementGuid>943ea86a-ff0d-4399-b3ac-13cdbb3f5a1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nawatable-row3-activation']</value>
      <webElementGuid>08aac52f-4bb8-4e14-8083-6a914d31ab71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nawatable-container-Group Menu']/div[4]/div/table/tbody/tr[3]/td[9]/button[4]</value>
      <webElementGuid>f817684f-c505-48aa-a666-db0131ea5f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[3]/following::button[4]</value>
      <webElementGuid>56e1c182-c2cb-4467-bafd-55f0ce59e0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ops Team Maker'])[1]/following::button[4]</value>
      <webElementGuid>3df91098-b2f4-436f-8236-bf6e347fd152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ops Team Checker'])[1]/preceding::button[1]</value>
      <webElementGuid>8fa4b5c6-eacc-4885-a85e-f821ef97d1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[4]/preceding::button[1]</value>
      <webElementGuid>80cc1413-57a4-4305-8c51-626bd4b93423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[9]/button[4]</value>
      <webElementGuid>0de0a26b-f60d-4959-ade9-9fdd91d12ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'nawatable-row3-activation']</value>
      <webElementGuid>f69cdf7a-952d-4d21-971a-f9e14548aec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
