<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pending To Approval</name>
   <tag></tag>
   <elementGuidId>b52acf37-0f91-4f53-960b-abe236cd9931</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiPaper-root.MuiAlert-root.MuiAlert-filledSuccess.jss2330.MuiPaper-elevation6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4df1af4-5cf4-4d60-bcb3-f2db3e946f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiPaper-root MuiAlert-root MuiAlert-filledSuccess jss2330 MuiPaper-elevation6</value>
      <webElementGuid>2b0dd1fa-9a15-4446-b800-bfe6f67ccc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>4b314305-a5a1-4131-be09-99b119048656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>direction</name>
      <type>Main</type>
      <value>down</value>
      <webElementGuid>be6cb26e-9386-4a8a-bbb8-636df4a15f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending To Approval</value>
      <webElementGuid>ec405044-78df-4b88-8b92-4d080b5d0b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiSnackbar-root MuiSnackbar-anchorOriginTopCenter&quot;]/div[@class=&quot;MuiPaper-root MuiAlert-root MuiAlert-filledSuccess jss2330 MuiPaper-elevation6&quot;]</value>
      <webElementGuid>bfac000f-ca29-41d4-9bf2-01c3f571156b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div</value>
      <webElementGuid>78601684-6c55-4413-9508-f97cd6228225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Channeling'])[1]/preceding::div[4]</value>
      <webElementGuid>01ff4a37-6715-4395-8d8b-8ba6ca0c139c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>13d0fbdf-6f56-40b8-b581-ffe7cd0cd630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pending To Approval' or . = 'Pending To Approval')]</value>
      <webElementGuid>2351e2a4-8db0-433f-b572-67a1826d3316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
