<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pending To Approval</name>
   <tag></tag>
   <elementGuidId>31442d65-22e8-41a6-97a4-453d506ecacc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiPaper-root.MuiAlert-root.MuiAlert-filledSuccess.jss2330.MuiPaper-elevation6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5cecec64-94a8-453f-b072-3edd406632d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiPaper-root MuiAlert-root MuiAlert-filledSuccess jss2330 MuiPaper-elevation6</value>
      <webElementGuid>df8c98cf-8400-4aa1-9565-f55ca5eb58c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>ba7555e9-8366-47ca-a594-3b6e538452c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>direction</name>
      <type>Main</type>
      <value>down</value>
      <webElementGuid>3d634437-341d-46a6-b737-08f1ca648041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending To Approval</value>
      <webElementGuid>634b54dc-232b-4de3-ad6d-6ca1dd1204e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiSnackbar-root MuiSnackbar-anchorOriginTopCenter&quot;]/div[@class=&quot;MuiPaper-root MuiAlert-root MuiAlert-filledSuccess jss2330 MuiPaper-elevation6&quot;]</value>
      <webElementGuid>39ba2c98-dd4a-43ae-8fc6-7c0f375fe64c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div</value>
      <webElementGuid>4b7c1a48-0a5d-4fd6-850f-7bd19195aa78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Channeling'])[1]/preceding::div[4]</value>
      <webElementGuid>acf04460-06c3-4dc4-b7da-8a7145f496f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>19c52d79-4f93-49b1-b80c-f5c612dd43ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pending To Approval' or . = 'Pending To Approval')]</value>
      <webElementGuid>f3c5bcbb-4a7d-4f64-a3e5-e9e769fcea88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
