<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Between_ant-input-number-input</name>
   <tag></tag>
   <elementGuidId>3c9dcc15-b569-4e48-8b27-aca91ad6cb77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input-number-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fd7ef4d-b5be-417c-99d8-a8cd6f041f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2f9d27a8-37ab-4a02-a73a-7abdfb1a43ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>191c5fc5-469c-4a00-9cba-0a9965d2a004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>66d1a5c2-7fc1-44de-a524-1e0da5bf044f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>795650d1-2644-4a1d-a379-9af61c8ddcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter number from</value>
      <webElementGuid>7cabb836-b1cc-47b9-96b2-38a8e84afe7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>8b612201-d0b2-445f-9ed5-7999365c0ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper&quot;]/div[@class=&quot;MuiPaper-root MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm MuiPaper-elevation24 MuiPaper-rounded&quot;]/div[@class=&quot;MuiDialogContent-root&quot;]/div[@class=&quot;query-builder&quot;]/div[@class=&quot;group-or-rule-container group-container&quot;]/div[@class=&quot;group group-or-rule&quot;]/div[@class=&quot;group--children hide--line one--child&quot;]/div[@class=&quot;group-or-rule-container rule-container&quot;]/div[@class=&quot;rule group-or-rule&quot;]/div[@class=&quot;rule--body--wrapper&quot;]/div[@class=&quot;rule--body&quot;]/div[@class=&quot;rule--value&quot;]/div[@class=&quot;rule--widget rule--widget--NUMBER&quot;]/div[@class=&quot;widget--widget&quot;]/div[@class=&quot;ant-col&quot;]/div[@class=&quot;ant-input-number ant-input-number-sm ant-input-number-focused&quot;]/div[@class=&quot;ant-input-number-input-wrap&quot;]/input[@class=&quot;ant-input-number-input&quot;]</value>
      <webElementGuid>f5fb99a5-4293-4d3e-adb9-e437fe577134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[15]</value>
      <webElementGuid>0713563b-e7dd-460b-81f8-e64e197905a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/input</value>
      <webElementGuid>957d8273-8c9e-4ae0-ac97-6b4dd51198eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter number from']</value>
      <webElementGuid>c48a5543-1360-43ab-bd83-df1cb5f4faca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
