<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Harga</name>
   <tag></tag>
   <elementGuidId>6d0bd3c4-5f51-4d63-8055-2bdfcecaaedf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h6[@data-unify = 'Typography' and (text() = 'Harga' or . = 'Harga')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>ecb02413-e8de-4613-b08a-3f0ab2fedcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>3da94aa3-d635-4929-8c2d-d3baa37f3d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harga</value>
      <webElementGuid>76d99e0c-d061-41cc-90d9-74baa02d5069</webElementGuid>
   </webElementProperties>
</WebElementEntity>
