<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Toko</name>
   <tag></tag>
   <elementGuidId>05cfae6d-b9de-4e36-bece-138cb7cac16c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-gjd4q1.e184mv6l0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div/div/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-testid = 'btnSRPShopTab' and (text() = 'Toko' or . = 'Toko')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e34c78e-8e47-46e5-a196-5adfd1eb8bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnSRPShopTab</value>
      <webElementGuid>4e9fdd4a-44bd-4973-b13f-e1e0f796c8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-gjd4q1 e184mv6l0</value>
      <webElementGuid>eb5df76f-9f85-455f-b886-75e2c2a778c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toko</value>
      <webElementGuid>e7611948-84b0-4600-bf02-a9b2ba189756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[@class=&quot;css-pz4z50&quot;]/div[@class=&quot;css-1yus67o&quot;]/button[@class=&quot;css-gjd4q1 e184mv6l0&quot;]</value>
      <webElementGuid>72992ad9-4fc8-4193-88bc-5e469a66de4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div/div/button[2]</value>
      <webElementGuid>e9b3ec35-cda1-4e8e-b9a7-11e36ab3141d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::button[1]</value>
      <webElementGuid>a7230f09-6679-4819-b526-76552556f868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terakhir ditambahkan'])[1]/following::button[6]</value>
      <webElementGuid>86b9e014-12ab-4e5b-9ddf-ca62b7071f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>39e69665-2ca7-4ba0-aec7-701d48b03917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Toko' or . = 'Toko')]</value>
      <webElementGuid>0c793905-de37-4a82-a411-2c6e18179050</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
