<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Produk</name>
   <tag></tag>
   <elementGuidId>4fc3e6f8-3f1c-41ce-89ae-1a5c298b7d45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-rjanld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43044aab-e221-49f0-8f93-70726903e2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-rjanld</value>
      <webElementGuid>da447034-9c11-49bb-90a2-72745dbf1819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProdukTokoMenampilkan 1 - 60 barang dari total 13.8jt+ untuk &quot;Meja&quot;Urutkan:Paling SesuaiPaling SesuaiUlasanTerbaruHarga TertinggiHarga TerendahDipromosikan olehPromosi oleh Topads berdasarkan minatmuBaca SelengkapnyaHomedoki IndonesiaCashback 4%Gratis OngkirBelanja di Homedoki Indonesia, diskon hingga 50%!Cek SekarangMeja anak-anak / Meja Belajar / Meja Tulis/ Meja belajar minimalis - Merah Muda, BesarRp 646.80051%Rp 1.320.0004.6Terjual 250+Meja Belajar / Meja Kantor / Meja Kayu Minimalis / Meja Kerja - WOOD+SHELFRp 690.00047%Rp 1.300.0004.7Terjual 750+Meja Komputer / Gaming Table/ Meja Belajar / Meja Kerja Meja PC Gaming - Black, SRp 650.00057%Rp 1.500.0004.6Terjual 750+Admeja laptop side table minimalis meja kerja meja komputer meja kantorRp200.000Kab. JeparaARS-furniture4.8Terjual 30+AdHL SalebrationsMeja / Meja Makan / Meja Komputer / Meja Gaming / Meja Kantor - A-100*45Rp255.00054%Rp560.000TangerangHomedoki Indonesia4.7Terjual 2 rb+AdOCADO - Meja balajar / rak penyimpanan multifungsi / meja laptop - cokelat 80*40Rp399.000CashbackKab. TangerangKeessonHome5.0Terjual 5AdHome SalebrationMeja Belajar / Meja Kantor / Meja Kayu Minimalis / Meja Kerja - WOOD+SHELFRp690.00047%Rp1.300.000TangerangHomedoki Indonesia4.7Terjual 750+AdHome SalebrationMeja Lipat Meja Kayu Meja Motif Kayu Meja Pelatihan SerbagunaRp260.0005%Rp275.000Jakarta UtaraDDS Infinity4.6Terjual 500+CEO Meja Lipat Camping Outdoor Portable Meja Koper SerbagunaRp209.00054%Rp458.000TangerangCEO Official Store4.8Terjual 250+Home SalebrationMeja Lipat Bentuk Koper (Portable) Cocok utk Jualan dan PameranRp300.0003%Rp310.000Jakarta BaratMinisweet_olshop4.9Terjual 7 rb+Home SalebrationIKEA LINNMON Meja Minimalis Berkualitas Putih 100x60 cmRp579.000CashbackKab. BekasiIKEA Indonesia4.7Terjual 100+Home SalebrationMeja Lipat Meja Kayu Meja Motif Kayu Meja Pelatihan SerbagunaRp260.0005%Rp275.000Jakarta UtaraDDS Infinity4.6Terjual 500+Home SalebrationMeja Lipat Dinding 60 x 30 cmRp100.000CashbackJakarta TimurRoboman Official4.9Terjual 750+</value>
      <webElementGuid>ee323f0d-521a-424c-a883-25b8288d505a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]</value>
      <webElementGuid>b755d44b-4e0d-4e36-8af6-3b87b1544d21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]</value>
      <webElementGuid>aa429d4e-da47-4796-87cf-0f027c253665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terakhir ditambahkan'])[1]/following::div[9]</value>
      <webElementGuid>e4c66a2f-ebac-4473-bde7-a6cb59bd0746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dilayani Tokopedia'])[1]/following::div[10]</value>
      <webElementGuid>a6f24705-1869-4a8c-9919-3f822cd43103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>3cbf3fd4-bc7b-48d2-98fc-240c5475ad71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ProdukTokoMenampilkan 1 - 60 barang dari total 13.8jt+ untuk &quot;Meja&quot;Urutkan:Paling SesuaiPaling SesuaiUlasanTerbaruHarga TertinggiHarga TerendahDipromosikan olehPromosi oleh Topads berdasarkan minatmuBaca SelengkapnyaHomedoki IndonesiaCashback 4%Gratis OngkirBelanja di Homedoki Indonesia, diskon hingga 50%!Cek SekarangMeja anak-anak / Meja Belajar / Meja Tulis/ Meja belajar minimalis - Merah Muda, BesarRp 646.80051%Rp 1.320.0004.6Terjual 250+Meja Belajar / Meja Kantor / Meja Kayu Minimalis / Meja Kerja - WOOD+SHELFRp 690.00047%Rp 1.300.0004.7Terjual 750+Meja Komputer / Gaming Table/ Meja Belajar / Meja Kerja Meja PC Gaming - Black, SRp 650.00057%Rp 1.500.0004.6Terjual 750+Admeja laptop side table minimalis meja kerja meja komputer meja kantorRp200.000Kab. JeparaARS-furniture4.8Terjual 30+AdHL SalebrationsMeja / Meja Makan / Meja Komputer / Meja Gaming / Meja Kantor - A-100*45Rp255.00054%Rp560.000TangerangHomedoki Indonesia4.7Terjual 2 rb+AdOCADO - Meja balajar / rak penyimpanan multifungsi / meja laptop - cokelat 80*40Rp399.000CashbackKab. TangerangKeessonHome5.0Terjual 5AdHome SalebrationMeja Belajar / Meja Kantor / Meja Kayu Minimalis / Meja Kerja - WOOD+SHELFRp690.00047%Rp1.300.000TangerangHomedoki Indonesia4.7Terjual 750+AdHome SalebrationMeja Lipat Meja Kayu Meja Motif Kayu Meja Pelatihan SerbagunaRp260.0005%Rp275.000Jakarta UtaraDDS Infinity4.6Terjual 500+CEO Meja Lipat Camping Outdoor Portable Meja Koper SerbagunaRp209.00054%Rp458.000TangerangCEO Official Store4.8Terjual 250+Home SalebrationMeja Lipat Bentuk Koper (Portable) Cocok utk Jualan dan PameranRp300.0003%Rp310.000Jakarta BaratMinisweet_olshop4.9Terjual 7 rb+Home SalebrationIKEA LINNMON Meja Minimalis Berkualitas Putih 100x60 cmRp579.000CashbackKab. BekasiIKEA Indonesia4.7Terjual 100+Home SalebrationMeja Lipat Meja Kayu Meja Motif Kayu Meja Pelatihan SerbagunaRp260.0005%Rp275.000Jakarta UtaraDDS Infinity4.6Terjual 500+Home SalebrationMeja Lipat Dinding 60 x 30 cmRp100.000CashbackJakarta TimurRoboman Official4.9Terjual 750+' or . = 'ProdukTokoMenampilkan 1 - 60 barang dari total 13.8jt+ untuk &quot;Meja&quot;Urutkan:Paling SesuaiPaling SesuaiUlasanTerbaruHarga TertinggiHarga TerendahDipromosikan olehPromosi oleh Topads berdasarkan minatmuBaca SelengkapnyaHomedoki IndonesiaCashback 4%Gratis OngkirBelanja di Homedoki Indonesia, diskon hingga 50%!Cek SekarangMeja anak-anak / Meja Belajar / Meja Tulis/ Meja belajar minimalis - Merah Muda, BesarRp 646.80051%Rp 1.320.0004.6Terjual 250+Meja Belajar / Meja Kantor / Meja Kayu Minimalis / Meja Kerja - WOOD+SHELFRp 690.00047%Rp 1.300.0004.7Terjual 750+Meja Komputer / Gaming Table/ Meja Belajar / Meja Kerja Meja PC Gaming - Black, SRp 650.00057%Rp 1.500.0004.6Terjual 750+Admeja laptop side table minimalis meja kerja meja komputer meja kantorRp200.000Kab. JeparaARS-furniture4.8Terjual 30+AdHL SalebrationsMeja / Meja Makan / Meja Komputer / Meja Gaming / Meja Kantor - A-100*45Rp255.00054%Rp560.000TangerangHomedoki Indonesia4.7Terjual 2 rb+AdOCADO - Meja balajar / rak penyimpanan multifungsi / meja laptop - cokelat 80*40Rp399.000CashbackKab. TangerangKeessonHome5.0Terjual 5AdHome SalebrationMeja Belajar / Meja Kantor / Meja Kayu Minimalis / Meja Kerja - WOOD+SHELFRp690.00047%Rp1.300.000TangerangHomedoki Indonesia4.7Terjual 750+AdHome SalebrationMeja Lipat Meja Kayu Meja Motif Kayu Meja Pelatihan SerbagunaRp260.0005%Rp275.000Jakarta UtaraDDS Infinity4.6Terjual 500+CEO Meja Lipat Camping Outdoor Portable Meja Koper SerbagunaRp209.00054%Rp458.000TangerangCEO Official Store4.8Terjual 250+Home SalebrationMeja Lipat Bentuk Koper (Portable) Cocok utk Jualan dan PameranRp300.0003%Rp310.000Jakarta BaratMinisweet_olshop4.9Terjual 7 rb+Home SalebrationIKEA LINNMON Meja Minimalis Berkualitas Putih 100x60 cmRp579.000CashbackKab. BekasiIKEA Indonesia4.7Terjual 100+Home SalebrationMeja Lipat Meja Kayu Meja Motif Kayu Meja Pelatihan SerbagunaRp260.0005%Rp275.000Jakarta UtaraDDS Infinity4.6Terjual 500+Home SalebrationMeja Lipat Dinding 60 x 30 cmRp100.000CashbackJakarta TimurRoboman Official4.9Terjual 750+')]</value>
      <webElementGuid>bc252cb8-da3d-4011-9154-161f5c7a2f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
