<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Harga Minimum</name>
   <tag></tag>
   <elementGuidId>e03aadd7-c20c-4e08-8f78-1bba37a9e75a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@data-unify = 'TextField' and @name = 'pmin' and @type = 'text' and @data-testid = 'iptSRPMinPriceFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf9fee6a-d820-46b3-b091-1e590b911ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>01c26d77-5f0f-49b7-84aa-8e3f2ef1d5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pmin</value>
      <webElementGuid>3106bcef-6ced-42cc-b92a-16e13d5e45ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1398ca1d-bd89-4b06-a604-9ca6dadc8568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>iptSRPMinPriceFilter</value>
      <webElementGuid>cdf5bdc9-e70a-4957-aebf-e7670d6e01db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
