<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Harga Maksimum</name>
   <tag></tag>
   <elementGuidId>fccd9ec0-ec10-4a00-a89d-43e32dc4e9a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@data-unify = 'TextField' and @name = 'pmax' and @type = 'text' and @data-testid = 'iptSRPMinPriceFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c7eaa12-7ae8-4f63-b7b8-ecee26d0a56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>e20ab164-75e6-4132-b15d-3fc952e0d45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pmax</value>
      <webElementGuid>774395ae-eeef-4cf1-ab35-dd130d41f97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bde52d4-9130-4876-91bd-6b99e7e860c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>iptSRPMaxPriceFilter</value>
      <webElementGuid>2db14678-9932-4772-be2f-78199a63c832</webElementGuid>
   </webElementProperties>
</WebElementEntity>
