<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2000</name>
   <tag></tag>
   <elementGuidId>9127c22e-2f95-4a4d-bb31-5c9b72f481a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[(text() = '2001' or . = '2001')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>19098e40-3c85-46d0-86be-927b70165628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2001</value>
      <webElementGuid>2d5fbfcd-bf70-48ab-ae73-6f31e3ea92d3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
