<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2002</name>
   <tag></tag>
   <elementGuidId>26262ffd-7784-4aa5-ac89-9a0829364e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[(text() = '2002' or . = '2002')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>617ac333-eb39-4395-99af-3174c3acf65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2002</value>
      <webElementGuid>1fc56254-f4b1-4483-8c49-f6048b3c1324</webElementGuid>
   </webElementProperties>
</WebElementEntity>
