<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dec</name>
   <tag></tag>
   <elementGuidId>312a563a-3759-4462-a6a1-8bffdb33bc87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[(text() = 'Dec' or . = 'Dec')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9e78d494-1221-42f4-9d6d-eb33f9da4118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dec</value>
      <webElementGuid>9dbf9bca-c651-4faf-8a64-5015efed15c9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
