<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Feb</name>
   <tag></tag>
   <elementGuidId>3ca7f6cf-380e-45ed-8207-c7c01f814a92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[(text() = 'Feb' or . = 'Feb')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9c4bba9a-c688-44ce-98cf-23087ece8be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Feb</value>
      <webElementGuid>c7ca7a19-ccd0-4447-84d5-35645963f704</webElementGuid>
   </webElementProperties>
</WebElementEntity>
