<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Jul</name>
   <tag></tag>
   <elementGuidId>d411b0a2-cb59-4d88-a3a8-9708528e11b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d0fbacf3-8530-492a-be0a-2056ef97252f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jul</value>
      <webElementGuid>bb255614-ea7a-497f-92f5-3ceccc078dae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
