<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Jun</name>
   <tag></tag>
   <elementGuidId>5fbbd818-95be-4b46-ab8b-353fc592f014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[(text() = 'Jun' or . = 'Jun')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>126b1658-7cf7-4b91-b0b0-b3d938115114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jun</value>
      <webElementGuid>c0ae1876-bfc2-43b8-a239-ba454f673f07</webElementGuid>
   </webElementProperties>
</WebElementEntity>
