<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Oct</name>
   <tag></tag>
   <elementGuidId>4bce49f4-a6ad-4ac0-a60d-9a6d52209ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cf97e98e-3eba-49ca-85be-66f5929c61db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oct</value>
      <webElementGuid>f28e9049-4cb4-48c4-9ca6-96aa1bcd51b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
